academy-service: cd .\services\academy-service\ && air
competition-service: cd .\services\competition-service\ && air
gateway: cd .\services\gateway\ && air
identity-service: cd .\services\identity-service\ && air
log-service: cd .\services\log-service\ && air
meta-service: cd .\services\meta-service\ && air
scout-service: cd .\services\scout-service\ && air
sport-service: cd .\services\sport-service\ && air
venue-service: cd .\services\venue-service\ && air