@echo off
echo Running all unit tests across all microservices and shared packages...
go test ./services/academy-service/... ./services/attachment-service/... ./services/competition-service/... ./services/venue-service/... ./services/gateway/... ./services/identity-service/... ./services/log-service/... ./services/meta-service/... ./services/scout-service/... ./services/sport-service/... ./shared/...
