syntax = "proto3";

package user.v1;

option go_package = "microservice-golang/gen/user/v1;userv1";

import "buf/validate/validate.proto";

// ─── Messages ─────────────────────────────────────────────────────────────────

message UserInternal {
  string id              = 1;
  string email           = 2;
  string username        = 3;
  string full_name       = 4;
  string hashed_password = 5;
  string status          = 6;
  string active_profile  = 7;
  repeated string role_ids = 8;
}

// ─── Requests/Responses ───────────────────────────────────────────────────────

message GetUserByEmailInternalRequest {
  string email = 1 [(buf.validate.field).string.email = true];
}

message GetUserByEmailInternalResponse {
  UserInternal user = 1;
}

message GetUserByIDInternalRequest {
  string id = 1 [(buf.validate.field).string.uuid = true];
}

message GetUserByIDInternalResponse {
  UserInternal user = 1;
}

// ─── Service ──────────────────────────────────────────────────────────────────

service UserInternalService {
  rpc GetUserByEmailInternal (GetUserByEmailInternalRequest) returns (GetUserByEmailInternalResponse);
  rpc GetUserByIDInternal    (GetUserByIDInternalRequest)    returns (GetUserByIDInternalResponse);
}