syntax = "proto3";

package user.v1;

option go_package = "microservice-golang/gen/user/v1;userv1";

import "buf/validate/validate.proto";
import "rbac/v1/role.proto";

// ─── Message ──────────────────────────────────────────────────────────────────

message UserInternal {
  string id                = 1;
  string email             = 2;
  string username          = 3;
  string full_name         = 4;
  repeated rbac.v1.Role roles = 5;
  string hashed_password   = 6;
}

// ─── Requests/Responses ───────────────────────────────────────────────────────

message GetUserByEmailInternalRequest {
  string email = 1 [(buf.validate.field).string.email = true];
}

message GetUserByEmailInternalResponse {
  UserInternal user = 1;
}

// ─── Service ──────────────────────────────────────────────────────────────────

service UserInternalService {
  rpc GetUserByEmailInternal (GetUserByEmailInternalRequest) returns (GetUserByEmailInternalResponse);
}
